
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/constell
    username: postgres
    password: benaynconstell
    driverClassName: org.postgresql.Driver


server:
  email: product@product.com
  cluster:
    - ip: 127.0.0.1
      path: /product1
    - ip: 127.0.0.2
      path: /product2
    - ip: 127.0.0.3
      path: /product3