
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/constell
    username: foo
    password: bar
    driverClassName: org.postgresql.Driver


server:
  email: test@test.com
  cluster:
    - ip: 127.0.0.1
      path: /test1
    - ip: 127.0.0.2
      path: /test2
    - ip: 127.0.0.3
      path: /test3