
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/constell
    username: postgres
    password: benaynconstell
    driverClassName: org.postgresql.Driver


server:
  email: dev@dev.com
  cluster:
    - ip: 127.0.0.1
      path: /dev1
    - ip: 127.0.0.2
      path: /dev2
    - ip: 127.0.0.3
      path: /dev3