spring:
  messages:
    basename: i18n/messages
  profiles:
    active: @profileActive@
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    # cache: false, Enable thymeleaf reloadable when develop, (⌘+F9)
    cache: false
    servlet:
      content-type: text/html

capricorn:
  configurer:
    clientId: constellation-capricorn
    clientSecret: 9ddf1f40ddea06837257a7e2653a69d0
    staticResourcePrefixes:
    - /module/
    - /components/
    - /assets/
    - /manages/
    staticResourceSuffixes:
    - .png
    - .woff2
    - .js
    - .css


server:
  port: 8011
  oauth:
    token:
      url: http://127.0.0.1:${server.port}/oauth/token

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    com.benayn.constell: INFO
    com.benayn.constell.services.capricorn.repository.mapper: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36}:%line - %msg%n"
  file: /Users/paulo/Documents/opt/logs/constell.log

mybatis:
  type-aliases-package: com.benayn.constell.services.capricorn.mapper
  mapper-locations: classpath:mybatis/mapper/*.xml

# OAuth2 resources are protected by a filter chain with order security.oauth2.resource.filter-order
# and the default is after the filter protecting the actuator endpoints by default
# http://docs.spring.io/spring-boot/docs/2.0.0.M3/reference/htmlsingle/#boot-features-security-oauth2-resource-server
security:
  sessions: never
  oauth2:
    resource:
      filter-order: 3
